name: API Tests

on:
  push:
    branches: [ master ]
  pull_request:  # This triggers workflow on push to any branch and pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Newman
        run: |
          curl -L https://raw.githubusercontent.com/Newman-co/newman/master/install.sh | bash
      - name: Run Newman Tests
        run: newman run api_tests.json
